### ISSUE TITLE
TMFS: Add a setting Staff view not working

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#104]
https://themachinefolksession.org/tune/147

When I click on the Staff button this is what shows. Also, does this part of the page have playback? Like, if I change the abc there I can play back the tune? Those controls are missing too.

![image](https://user-images.githubusercontent.com/10271332/43243386-cd3513d2-90a6-11e8-9382-194ac0496d1d.png)

**Comment by tobyspark** [comment]
Not sure what's going on here. It worked fine last I looked, and yes with full playback, highlighting etc.

**Comment by boblsturm** [comment]
I also tried added a setting with a specific tempo but it didn't take, e.g., here: https://themachinefolksession.org/tune/149
I had to add the tempo manually.

**Comment by tobyspark** [comment]
I just tried, and it all works for me. Will try with e.g. Chrome when I've got a desk to sit at...

**Comment by tobyspark** [comment]
Just had another go. Works for me. Could you somehow show it to me not working? Note Quicktime Player has "New Screen Recording" in the File menu.

(plus I added your title to your Silver Keyboard setting via the admin site)

**Comment by boblsturm** [comment]
Just submitted a setting of this https://themachinefolksession.org/tune/248 with quaver=200 and it puts it in there, but the tempo it plays back is not right.
![screen shot 2018-09-19 at 11 08 03 am](https://user-images.githubusercontent.com/10271332/45743489-6b3b4800-bbfc-11e8-9c15-c60b152aa570.png)

**Comment by tobyspark** [comment]
Can you make a new issue about tempo? And be a bit more precise, e.g. does the playback speed up / slow down as the tempo number gets bigger and smaller (good) but the actual speed isn't right (bad) or it's correct for some time signatures and not for others...

**Comment by boblsturm** [comment]
Just submitted a setting of this https://themachinefolksession.org/tune/248 with quaver=200 and it puts it in there, but the tempo it plays back is not right.
