### ISSUE TITLE
TMFS: Add setting Title field did not carry over

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#105]
![image](https://user-images.githubusercontent.com/10271332/43243533-6be1acf2-90a7-11e8-808b-c942bcd1676b.png)

I added the title, but it did not carry over when I submitted

![image](https://user-images.githubusercontent.com/10271332/43243551-7f5c64f2-90a7-11e8-950d-7067bfcd438f.png)

**Comment by tobyspark** [comment]
Hmm. The title should be displayed to the left. Will investigate.

**Comment by tobyspark** [comment]
I've updated a thing or two for the 'add setting' gubbins. Which might have fixed this, without knowing exactly what the cause was. Could you try and re-create, and if you can re-create, note down the steps?
