### ISSUE TITLE
TMFS: Add anchors to links to settings

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#106]
Would be nice to have anchors so that links can be refer to settings rather than just the page.

![image](https://user-images.githubusercontent.com/10271332/43244421-e0a90dac-90aa-11e8-951c-db3f5e0163f8.png)

**Comment by tobyspark** [comment]
Strictly speaking, there are anchors: https://themachinefolksession.org/tune/147#setting-1

But yes, links to be clicked on / copied and pasted.

**Comment by tobyspark** [comment]
Fixed in #119
