### ISSUE TITLE
TMFS: Add S: prime tokens information to tunes and settings

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#107]
Downloading the ABC of the original tune https://themachinefolksession.org/tune/147 I find it does not have the S: prime token text, etc.

Currently, the top of the ABC for the above is
X:147
T:The Silver Keyboard
S:Tune #147 archived at The Machine Folk Session
F://themachinefolksession.org/tune/147

but it should be
X:147
T:The Silver Keyboard
S:Tune #147 archived at The Machine Folk Session (http://themachinefolksession.org/tune/147)
S:Generated at http://folkrnn.org using the thesession_with_repeats model with RNN seed = 238743; temperature = 1.0; prime tokens = M:6/8 K:Cmaj |: E D C E C C | G A G c F F |

**Comment by tobyspark** [comment]
ABC downloads with
S - MachineFolk slug
F - MachineFolk URL
which are the appropriate uses of those fields, as per spec. If there were any information fields in the submitted ABC, these become N fields, for notes.

I can add an N field for the folkrnn parameters. I hadn't as it's redundant given the MachineFolk page has that info, but it could be included.

**Comment by boblsturm** [comment]
Yes, they need to be preserved in the ABC because people will download that material.

**Comment by tobyspark** [comment]
FYI The code is here: https://github.com/tobyspark/folk-rnn-webapp/blob/5c67814fd47ebf3136a312987ba043dff88538b4/folk_rnn_site/archiver/models.py#L94

**Comment by tobyspark** [comment]
Fixed in #119
