### ISSUE TITLE
TMFS: Admin views of user's submission

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#108]
It would be great to see what a particular user has submitted to the website.

**Comment by tobyspark** [comment]
Each member has a public page, e.g. `https://themachinefolksession.org/member/1`

The idea of that page is to show all they've done, and give a preview of their tunebook. To do this properly will take activity-streams, 
https://github.com/tobyspark/folk-rnn-webapp/issues/91#issuecomment-405889505

This isn't an *admin* view, though. What's the use-case you have in mind?

**Comment by boblsturm** [comment]
OK. That's good, but how do I find the member number of a particular user?

**Comment by tobyspark** [comment]
Good question. It’s, ah, in the admin page URL.

**Comment by boblsturm** [comment]
So I found the member, but searching on their name returns nothing. They have contributed several tunes. Searching on another name does return entires.

**Comment by tobyspark** [comment]
Searching should work, in the ‘user expects’ sense rather than ’technically it does’ sense. If memory serves, there’s a complication that first and last name are stored separately. I’ll have another look.

**Comment by tobyspark** [comment]
oh - and searching where? I was thinking /tunes

**Comment by boblsturm** [comment]
Search tunes for "Peter" and "Lili". The first works but the second does not, even though Lili has submitted several tunes (https://themachinefolksession.org/member/15)

**Comment by tobyspark** [comment]
Search issue fixed in 4679134
