### ISSUE TITLE
Disappearing tokens in postprocessing

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#11]
When I use the following as a seed, "G G | G 2 c c c 2 B c | d e f d e 4 | M:3/4", and set M:4/4 and K:Cmaj, I get the following output from my command line script:

M:4/4
K:Cmaj
GG|G2ccc2Bc|defde4|M:3/4GABc2d2|egdef2G2|G2ccc2Bc|defde4|eAAcdBGG|dedBc2d2|efede2d2|cdedc2G2|effde2G2|ddedc4|cdeff2fd|edeBd4|cdefg2A2|G2ABc2z2|

The web interface shows the M:3/4 is preserved, but then it disappears after finishing. It should remain.

Maybe something is wrong with the post-processing in consumers.py?

**Comment by tobyspark** [comment]
The buried meter token is removed in the `abc2abc` formatting of the rnn generated abc. 

It happens here: https://github.com/tobyspark/folk-rnn-webapp/blob/master/folk_rnn_site/composer/consumers.py#L77

So this behaviour is by-design. Note as well as what the webapp uses in the database, the raw abc and post-processed abc are archived to disk:
```
$ ls -l /var/opt/folk_rnn_task/tunes/
total 888
-rw-rw-r-- 1 vagrant vagrant  956 Feb 23 10:11 without_repeats_tallis_170
-rw-rw-r-- 1 vagrant vagrant 1552 Feb 23 10:11 without_repeats_tallis_170_raw
-rw-rw-r-- 1 vagrant vagrant  849 Feb 25 13:28 without_repeats_tallis_181
-rw-rw-r-- 1 vagrant vagrant 1431 Feb 25 13:28 without_repeats_tallis_181_raw
-rw-rw-r-- 1 vagrant vagrant  690 Feb 26 13:47 without_repeats_tallis_195
-rw-rw-r-- 1 vagrant vagrant 1155 Feb 26 13:47 without_repeats_tallis_195_raw
-rw-rw-r-- 1 vagrant vagrant  973 Feb 26 13:49 without_repeats_tallis_196
-rw-rw-r-- 1 vagrant vagrant 1698 Feb 26 13:49 without_repeats_tallis_196_raw
[...]
-rw-rw-r-- 1 vagrant vagrant  230 Feb 22 22:37 with_repeats_100
-rw-rw-r-- 1 vagrant vagrant  318 Feb 22 22:37 with_repeats_100_raw
-rw-rw-r-- 1 vagrant vagrant  215 Feb 22 22:40 with_repeats_101
-rw-rw-r-- 1 vagrant vagrant  296 Feb 22 22:40 with_repeats_101_raw
-rw-rw-r-- 1 vagrant vagrant  229 Feb 22 22:41 with_repeats_102
-rw-rw-r-- 1 vagrant vagrant  320 Feb 22 22:41 with_repeats_102_raw
-rw-rw-r-- 1 vagrant vagrant  230 Feb 22 22:46 with_repeats_103
-rw-rw-r-- 1 vagrant vagrant  324 Feb 22 22:46 with_repeats_103_raw
-rw-rw-r-- 1 vagrant vagrant  225 Feb 22 22:46 with_repeats_104
-rw-rw-r-- 1 vagrant vagrant  313 Feb 22 22:46 with_repeats_104_raw
-rw-rw-r-- 1 vagrant vagrant  247 Feb 22 22:46 with_repeats_105
[...]
```
