### ISSUE TITLE
TMFS: Tempo is not working

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#121]
The tempo is set to quaver=200 here https://themachinefolksession.org/tune/248#setting-1

But it is not playing it back that fast.

**Comment by tobyspark** [comment]
Any clues as to what it's doing wrong? A multiple of what it should be, etc.?

**Comment by boblsturm** [comment]
I see now. When just Q:200 is specified for 9/8 it says it is 200 quavers per minute. For a slip jig, it's more common to specifiy dotted crotchet, or Q:3/8=200 ... this may complicate things too much. Let's just leave as is.
