### ISSUE TITLE
abcjs player soundfont error

### ISSUE THREAD

**Issue by olets** [tobyspark/folk-rnn-webapp#146]
The abcjs webplayer isn't working for me on either folkrnn.org or themachinefolksession.org. Console error:

![image](https://user-images.githubusercontent.com/3282350/61185479-1a338f00-a628-11e9-8d5d-bd19db01366d.png)

**Comment by tobyspark** [comment]
Hmm.

It works for me, here. But looking at your console log it shouldn't be accessing the soundfonts on github. That could be a symptom of the problem.

To get any further, I'll need more information. To start: to be precise, the page appears to load normally (i.e. as per the demo video on the homepage), with score. You can download the midi. But when hitting play on the audio player, you hear nothing?

**Comment by olets** [comment]
Sorry for the delay.

To clarify: nope, the page loaded but the "compose" button had no effect: no url change, no content change in the main section of the page.

Looks like the issue was my Ghostery setup. But what, exactly, I'm not sure. I marked https://folkrnn.org/ as trusted, and the the sidebar "compose" app started working. 

Surprisingly, I then told Ghostery to "restrict" the site… and the app still works. Thought maybe it was because I still had the csrftoken, but it works even after I delete it. Oh well 🤷‍♂️ weird that I can't get it to stop working, but always working isn't so bad!

**Comment by olets** [comment]
Sorry, that wasn't accurate. Misremembered the full problem. The tune generation thing was about Ghostery. 

> the page appears to load normally (i.e. as per the demo video on the homepage), with score. You can download the midi. But when hitting play on the audio player, you hear nothing?

Correct, I hear nothing and there is a console error.

My previous comment was off, but again it's something about a Chrome extension: it works fine in an incognito window. I should have tried that first. User error!

**Comment by tobyspark** [comment]
Thanks for the update.
