### ISSUE TITLE
Page doesn't work in Safari or Chrome

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#71]
I can't get the page to work in Safari (v. 8.0.5) or Chrome (v. 67)

**Comment by boblsturm** [comment]
To be more clear, machine folk session.

**Comment by tobyspark** [comment]
Waa!? Can you copy and paste the URL you’re entering?

**Comment by boblsturm** [comment]
https://themachinefolksession.org

**Comment by tobyspark** [comment]
Works for me, in Chrome – which auto-updates so we'll both be running the latest.

I'm really not sure what's going on here. More detail needed. What does "doesn't work" mean? Blank? Server Error? etc.?

**Comment by boblsturm** [comment]
Here is how a tune appears on chrome. 
![pkcpc8ta2mqn4knv43fddlh6k9979l8n8](https://user-images.githubusercontent.com/10271332/42238862-7c30a95c-7f02-11e8-8f0d-08f4bc2fb0ef.png)

**Comment by tobyspark** [comment]
Coo. You're right, I must not have drilled down into a tune. The full abc there in Chrome doesn't render, when it does on Safari.

**Comment by tobyspark** [comment]
Ah. I see what's happening. The ABC doesn't render when logged out. And that's because the javascript on the page bails before it gets to the ABC rendering because it's looking for something that's only there when logged in.

**Comment by tobyspark** [comment]
Fixed in aefeb5b. Deployed.
