### ISSUE TITLE
Tune snippet on machine folk session not displaying correctly.

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#72]
![image](https://user-images.githubusercontent.com/10271332/42223254-9c080dcc-7ed7-11e8-93f7-5a6310430735.png)
Make sure the "L:1/8" is in the ABC.

**Comment by tobyspark** [comment]
That’s the one line preview, for which I cut out everything that (I thought) isn’t just the core display of that one line. Now comparing the actual tune page to the preview, I see you’re right. I’ll add that in.

**Comment by tobyspark** [comment]
Fixed in 6dbfd1fc2668afa1d27d07abb0771e5451e5a6ea

**Comment by boblsturm** [comment]
Maybe "L:1/8" should be added to everything?

**Comment by tobyspark** [comment]
I'm wary of adding it everywhere. It will make folkrnn and machinefolk behave differently to other sites. And... that's a lot of futzting.

**Comment by boblsturm** [comment]
True dat.
