### ISSUE TITLE
Forum functionality: Tune of the month

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#74]
I want to create something like a "tune of the month", like here: http://forum.melodeon.net/index.php/topic,22511.0.html

Users can vote on one of five selections to learn to play and upload their results by the end of the month to a forum, like here: http://forum.melodeon.net/index.php/topic,22404.0.html

**Comment by tobyspark** [comment]
UTC issue: a date-to-datetime-at-00:00 or -at-23:59 template tag

**Comment by tobyspark** [comment]
see #92
