### ISSUE TITLE
Machine Folk Session: Setting == original

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#89]
Users are creating settings that are exactly the same as the original, e.g., https://themachinefolksession.org/tune/123

Let's not allow this.

**Comment by tobyspark** [comment]
As I left the desk last night, I had "abc_tune_fingerprint" half written to re-work setting submission comparisons. So, yes.

**Comment by tobyspark** [comment]
Reworked in #90
