### ISSUE TITLE
TMFS: Preview doesn't work for some tunes

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#93]
For some tunes, the preview clip is not showing. Is that because of the chords?

![image](https://user-images.githubusercontent.com/10271332/43042972-58e4b78c-8d89-11e8-981e-9b7dfd94ff7c.png)

**Comment by tobyspark** [comment]
This tune has been edited to have invalid ABC (it wasn't like this before, I swear). The K information field is the last line of the header. Having the Q below it means the Q is in the body, and a) it then needs square brackets and b) a one-line preview of a tempo isn't much =]

Now... could the app hint to the user that the ABC is like this? Probably.
