### ISSUE TITLE
TMFS: Navigating tunebook

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#94]
I would like all pages to be linked here, e.g., instead of just just previous and next, put 1, 2, 3, 4, 5, 6, 7. Also, repeat this at the bottom of the page.

Also and option to view all on one page.

![image](https://user-images.githubusercontent.com/10271332/43059130-4b2f9586-8e4b-11e8-8af6-f50d5700a5b1.png)

**Comment by tobyspark** [comment]
Yep, this is reasonable. 'View all' might need some kind of limit to stop it consuming all resources and falling over.

**Comment by tobyspark** [comment]
<img width="242" alt="screen shot 2018-09-19 at 15 30 56" src="https://user-images.githubusercontent.com/197773/45760004-0f36ea80-bc21-11e8-9f95-29591d74bd82.png">

Not deployed yet, but some work has been done on this.

**Comment by tobyspark** [comment]
<img width="542" alt="screenshot 2018-10-25 at 14 32 33" src="https://user-images.githubusercontent.com/197773/47503882-04e0bf80-d863-11e8-9e89-39a0bc1523c1.png">

<img width="457" alt="screenshot 2018-10-25 at 14 32 39" src="https://user-images.githubusercontent.com/197773/47503883-05795600-d863-11e8-96ac-001edaea02f1.png">

**Comment by tobyspark** [comment]
Didn't like that in the end. Didn't fit visually.

<img width="471" alt="screenshot 2018-10-24 at 17 28 51" src="https://user-images.githubusercontent.com/197773/47503948-30fc4080-d863-11e8-842b-197fc8f07270.png">

That was better in terms of visual fit but still wasn't much help navigation wise (e.g. "next" not obvious and moved around). In the end, what really makes the difference is 'view all', and – I know realise – if made available to authenticated users only my abuse-the-server concerns go away.

**Comment by tobyspark** [comment]
<img width="485" alt="screenshot 2018-10-25 at 14 37 50" src="https://user-images.githubusercontent.com/197773/47504167-9ea86c80-d863-11e8-8097-e13333735eb2.png">

<img width="504" alt="screenshot 2018-10-25 at 14 37 58" src="https://user-images.githubusercontent.com/197773/47504168-9ea86c80-d863-11e8-9933-3eaf54b3c46f.png">



Implemented in #122

**Comment by boblsturm** [comment]
I like the ability to select a page before, a page after, beginning or end.
