### ISSUE TITLE
folkrnn.org add new models

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#98]
I have two other models to add:
1. version 1, which is a character-based model
2. version 3, which has a slightly different vocabulary from the current version...

How might we do this with the existing machinery?

**Comment by tobyspark** [comment]
Exciting. I like more models. And yes, this should be a test of existing machinery.

**Comment by tobyspark** [comment]
The machinery goes like so –

folkrnn.org, i.e. the `composer` app, dynamically creates it's list of models from the file system each time it is restarted. This module does that –
https://github.com/tobyspark/folk-rnn-webapp/blob/master/folk_rnn_site/composer/rnn_models.py

It expects pickles there in a certain format. I wrote a script to compile the two(?) Python v2 files the folkrnn used. And then the display name needs to be in there (it used to make one up from the filename, but e.g. `w/ :| |:` put an end to that!).
https://github.com/tobyspark/folk-rnn-webapp/blob/master/tools/create_model_from_config_meta.py

The procedure is
- Update folk-rnn (not folk-rnn-webapp) to have the model
- For each new model, add an item to the `metadata_paths` list in the `create_model` script.
- Run that script
- Add the resulting pickles to `/var/opt/folk-rnn-task/models`
...and all the models should be live.

There might well be something in these new models that the current machinery doesn't expect, but I can deal with that, and once dealt with any future models with that quirk should load fine.

**Comment by tobyspark** [comment]
Implemented, addressing many complications now handled for future cases, in #133, #134, #136, #138, #139, #140
